version: '3'

services:
  fastduno_database:
    image: postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  fastduno_app:
    image: fastduno_app
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - fastduno_database
    
volumes:
  pgdata: