version: '3'

services:
  fastduno_database:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  fastduno_app:
    image: fastduno_app
    entrypoint: ./entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - fastduno_database
    environment:
      DATABASE_URL: postgresql://app_user:app_password@fastduno_database:5432/app_db

volumes:
  pgdata: